hypehouse:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: ud42201.west-europe.azure


      # User credentials
      user: darkosnowflake
      password: Snowflake1!

      # Database and schema
      database: dev
      schema: dbt_darko
      warehouse: DBT_TRANSFORMING
      role: developer

    prd:
      type: snowflake
      account: ud42201.west-europe.azure

      # User credentials
      user: darkosnowflake
      password: Snowflake1!

      # Database and schema
      database: prd
      schema: prd
      warehouse: DBT_TRANSFORMING
      role: developer
