version: 2

models:
  - name: stg_comment_count
    description: "Transformed data from the comment_count table for staging."
    columns:
      - name: index
        description: "Original column 'index'."
      - name: comment_count
        description: "Original column 'comment_count_for_client_HyPeHoUsE'."
      - name: video_id
        description: "Original column 'video_id_for_client_HyPeHoUsE'."
        tests:
          - not_null

  - name: stg_likes_count
    description: "Transformed data from the likes_count table for staging."
    columns:
      - name: index
        description: "Original column 'index'."
      - name: dislikes
        description: "Original column 'dislikes_for_client_HyPeHoUsE'."
      - name: likes
        description: "Original column 'likes_for_client_HyPeHoUsE'."
      - name: trending_date
        description: "Original column 'trending_date_for_client_HyPeHoUsE'."
      - name: video_id
        description: "Original column 'video_id_for_client_HyPeHoUsE'."
        tests:
          - not_null
  - name: stg_video_info
    description: "Transformed data from the video_info table for staging."
    columns:
      - name: index
        description: "Original column 'index'."
      - name: categoryId
        description: "Original column 'categoryId_for_client_HyPeHoUsE'."
      - name: channelId
        description: "Original column 'channelId_for_client_HyPeHoUsE'."
      - name: channelTitle
        description: "Original column 'channelTitle_for_client_HyPeHoUsE'."
      - name: comments_disabled
        description: "Original column 'comments_disabled_for_client_HyPeHoUsE'."
      - name: description
        description: "Original column 'description_for_client_HyPeHoUsE'."
      - name: dislikes
        description: "Original column 'dislikes_for_client_HyPeHoUsE'."
      - name: garbled_1
        description: "Original column 'garbled_1_for_client_HyPeHoUsE'."
      - name: garbled_2
        description: "Original column 'garbled_2_for_client_HyPeHoUsE'."
      - name: garbled_3
        description: "Original column 'garbled_3_for_client_HyPeHoUsE'."
      - name: garbled_4
        description: "Original column 'garbled_4_for_client_HyPeHoUsE'."
      - name: garbled_5
        description: "Original column 'garbled_5_for_client_HyPeHoUsE'."
      - name: published_at
        description: "Original column 'publishedAt_for_client_HyPeHoUsE'."
      - name: ratings_disabled
        description: "Original column 'ratings_disabled_for_client_HyPeHoUsE'."
      - name: tags
        description: "Original column 'tags_for_client_HyPeHoUsE'."
      - name: thumbnail_link
        description: "Original column 'thumbnail_link_for_client_HyPeHoUsE'."
      - name: title
        description: "Original column 'title_for_client_HyPeHoUsE'."
      - name: trending_date
        description: "Original column 'trending_date_for_client_HyPeHoUsE'."
      - name: video_id
        description: "Original column 'video_id_for_client_HyPeHoUsE'."
        tests:
          - not_null
  - name: stg_view_count
    description: "Transformed data from the view_count table for staging."
    columns:
      - name: index
        description: "Original column 'index'."
      - name: trending_date
        description: "Original column 'trending_date_for_client_HyPeHoUsE'."
      - name: video_id
        description: "Original column 'video_id_for_client_HyPeHoUsE'."
        tests:
          - not_null
      - name: view_count
        description: "Original column 'view_count_for_client_HyPeHoUsE'."
