hypehouse:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: cs66148.west-europe.azure


      # User credentials
      user: darko
      password: Darkomind1!

      # Database and schema
      database: dev
      schema: dbt_darko
      warehouse: DBT_TRANSFORMING
      role: developer

    prd:
      type: snowflake
      account: cs66148.west-europe.azure

      # User credentials
      user: darko
      password: Darkomind1!

      # Database and schema
      database: prd
      schema: prd
      warehouse: DBT_TRANSFORMING
      role: developer

    # Additional environments (staging, etc.) can be added similarly
    